export TWITTER_CONSUMER_KEY=Q69JFxKponHTstUOKRJU93nJl
export TWITTER_CONSUMER_SECRET=IPlsxW2gJ8LpO7LytyEf1G3EedcQO3VfgnmCM3eRkNtk9lHhbN
export MAUTIC_PUBLIC_KEY='1_5lcng9h4j4840ck8gsowsgo0kcsc0cc4ckco4c4888cswsggkg'
export MAUTIC_SECRET_KEY='4wq5x3sbga2owco4sw0c0k4ss844cco4cskccw08kg4o4gow4k'
which /usr/libexec/java_home 1>/dev/null 2>&1 && export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$PATH:$HOME/Library/Activator/activator-dist-1.3.12/bin
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
which pyenv 1>/dev/null 2>&1 && eval "$(pyenv init -)"
export XDG_CONFIG_HOME=$HOME/.config
export PATH=$HOME/.rbenv/shims:$PATH
alias v="vim"
alias n="nvim"
alias alert="printf '\a'"
alias activo="cd $HOME/Activo/activo/documents; vagrant up; vagrant ssh"
export PATH=$HOME/Activo/activo/bin:$PATH
which hub 1>/dev/null 2>&1 && eval "$(hub alias -s)"
export XDG_CONFIG_HOME=$HOME/.config
alias ghc='stack ghc --'
alias ghci='stack ghci --'
alias runhaskell='stack runhaskell --'
alias py="python"
alias vimrc="nvim ~/.vimrc"
alias zshrc="nvim ~/.zshrc"
alias zshenv="nvim ~/.zshenv"
alias dein="nvim ~/.dein.toml"
alias deinl="nvim ~/.lazy_dain.toml"
alias pryrc="nvim ~/.pryrc"
alias latexrc="nvim ~/.latexmkrc"
alias col256='for c in {000..255}; do echo -n "\e[38;5;${c}m $c" ; [ $(($c%16)) -eq 15 ] && echo;done'
